# TODO:
#     1. update the local dtranx conf file: follow the 183-191 lines in Deploy.py in DTranx project
#           among the configurations, InitializeDB and PerfLog might be dynamically adjusted during the perf tests, so highlight these configurations
#     2. make it configurable as whether to recover the backup database or not. Follow the 48-80 lines in TestHelper.py in DTranx project
#     3. run dtranx service: follow the 193-214 lines in Deploy.py in DTranx project
---
- name: prepare to run DTranx
  shell: "ulimit -c unlimited; export LD_LIBRARY_PATH=$LD_LIBRARY_ATH:/usr/local/lib;"
  args:
    chdir: "{{dtranx_dir}}"

- name: run DTranx binary
  shell: "nohup ./DTranx -i ips -c DTranx.conf >> DTranx.log 2>&1 &"
  args:
    chdir: "{{dtranx_dir}}"

- name: core binding for zeromq
  shell: "./process.sh bind 1,21"
  args:
    chdir: "{{dtranx_dir}}"
  become: true
