---


- name: run bangdb slave
  command: "{{project_dir}}/bangdb-server/bangdb-server -i slave -r yes -t yes -s {{inventory_hostname}}:{{bangdb_port}} -m {{bangdb_server_ip}}:{{bangdb_port}}  -b yes"
  args:
    chdir: "{{project_dir}}/bangdb-server/"
  register: bangdb

- debug:
    msg: "{{bangdb.stdout}}"
