# TODO:
#     1. install locally: follow the 115-130 lines in Deploy.py in Logcabin project
#     2. install remotely: follow the 33 line in EnvSetup.py in DTranx project 

#     assume logcabin src is already located in ~/
---
- name: install logcabin libries
  copy:
    src: "{{logcabin_src_dir}}/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'build/liblogcabin.a', dest: '/usr/local/lib/'}
    - { src: 'build/liblogcabin.so', dest: '/usr/local/lib/'}
  become: true

- name: install logcabin binary
  copy:
    src: "{{logcabin_src_dir}}/build/LogCabin"
    dest: "{{logcabin_dir}}/"
    mode: preserve

- name: sudo ldconfig
  shell: sudo ldconfig
