---

- name: start hyperdex coordinator server
  hosts: hyperdex_coordinator
  gather_facts: false
  roles:
    - hyperdex-coordinator-run

- name: start hyperdex daemons server
  hosts: hyperdex_daemon
  gather_facts: false
  roles:
    - hyperdex-daemon-run

- name: Init hyperdex coordinator
  hosts: hyperdex_coordinator
  gather_facts: false
  roles:
    - hyperdex-init

- name: Backup hyperdex.db.bak on daemons
  hosts: hyperdex_daemon
  gather_facts: false
  roles:
    - hyperdex-backup

- name: check if hyerdex coordinator running
  hosts: hyperdex_coordinator
  gather_facts: false
  tasks:
    - raw: ps -A | grep replicant
      register: psout
      failed_when: "psout.rc==1"
      changed_when: false

- name: check if all hyerdex daemons  are running
  hosts: hyperdex_daemon
  gather_facts: false
  tasks:
    - raw: ps -A | grep hyperdex
      register: psout
      failed_when: "psout.rc==1"
      changed_when: false
