---

- name: check if hyerdex coordinator is running
  hosts: hyperdex_coordinator
  gather_facts: false
  tasks:
    - raw: ps -A | grep replicant
      register: psout
      failed_when: "psout.rc==1"
      changed_when: false
- name: check if all hyerdex daemons are running
  hosts: hyperdex_daemon
  gather_facts: false
  tasks:
    - raw: ps -A | grep hyperdex
      register: psout
      failed_when: "psout.rc==1"
      changed_when: false
