---

#- name: stop all hyperex server and coordinator
#  hosts: hyperdex_coordinator:hyperdex_daemon
#  gather_facts: false
#  roles:
#    - hyperdex-stop

- name: clean all hyperex server and coordinator except hyperdex.db.bak
  hosts: hyperdex_coordinator:hyperdex_daemon
  gather_facts: false
  roles:
    - roles/hyperdex/hyperdex-clean

# clean hyperdex.db.bak maybe irrevelant
