---

- name: start cockroach first node
  hosts: cockroach_first_node
  gather_facts: false
  roles:
    - roles/cockroach/cockroach-first-start

- name: start cockroach other nodes
  hosts: cockroach_other_nodes
  gather_facts: false
  roles:
    - roles/cockroach/cockroach-others-start

- name: start cockroach first node
  hosts: cockroach_first_node
  gather_facts: false
  roles:
    - roles/cockroach/cockroach-setup

