---

- name: copy and untar  BangDB 0.9 binary
  unarchive:
    src: bangdb-cs-linux-64-native-0.9.tar.gz
    dest: "{{project_dir}}"

- name: modify config maxs_laves
  lineinfile:
    path: "{{project_dir}}/bangdb-server/bangdb.config"
    regexp: '^MAX_SLAVES ='
    line: 'MAX_SLAVES = {{bangdb_slave_count}}'

- name: modify transaction type
  lineinfile:
    path: "{{project_dir}}/bangdb-server/bangdb.config"
    regexp: '^DB_TRAN_TYPE ='
    line: 'DB_TRAN_TYPE = DB_OPTIMISTIC_TRANSACTION'
