# TODO:
#     1. install locally: follow the 188-195 lines in EnvSetup.py in DTranx project
#     2. install remotely: copy the libdtranx.a and libdtranx.so to remote cluster servers under /usr/local/lib/ directory

#	assume Dtranx src is already located in ~/
- name: install dtranx libries
  copy:
    src: "{{dtranx_src_dir}}/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'Build/libdtranx.a', dest: '/usr/local/lib/'}
    - { src: 'Build/libdtranx.so', dest: '/usr/local/lib'}
  become: true

- name: install dtranx binary
  copy:
    src: "{{dtranx_src_dir}}/Build/DTranx"
    dest: "{{dtranx_dir}}/"
    mode: preserve

- name: sudo ldconfig
  shell: sudo ldconfig
