---

- name: create benchmark directory if not exist
  command: mkdir -p {{benchmark_dir}}

- name: create benchmark directory if not exist
  raw: rm {{benchmark_dir}}/{{server_ips_filename}}; touch {{benchmark_dir}}/{{server_ips_filename}}

- name: generate server ips
  raw: "echo {{item}} >> {{benchmark_dir}}/{{server_ips_filename}}"
  with_items: "{{servers}}"

- name: copy workload files
  copy:
    src: "{{ycsb_src_dir}}/{{item}}"
    dest: "{{benchmark_dir}}"
    mode: 0644
#  with_items: "{{workloads_path}}"
  with_items: "{{workload_files}}"

- name: copy ycsbc program
  copy:
    src: "{{ycsb_src_dir}}/ycsbc"
    dest: "{{benchmark_dir}}"
    mode: 0755

  
- name: create btree and rtree directory if not exist
  command: mkdir -p {{item}}
  with_items: 
    - "{{rtree_dir}}"
    - "{{btree_dir}}"

- name: copy btree programs
  copy:
    src: "{{item}}"
    dest: "{{btree_dir}}"
    mode: 0755
  with_fileglob:
    - "{{btree_src_dir}}/Build/BTreeMain"
    - "{{btree_src_dir}}/BTree.conf"

- name: copy rtree programs
  copy:
    src: "{{item}}"
    dest: "{{rtree_dir}}"
    mode: 0755
  with_fileglob:
    - "{{rtree_src_dir}}/Build/RTreeMain"
    - "{{rtree_src_dir}}/RTree.conf"

- name: install related libs
  copy:
    src: "{{item}}"
    dest: /usr/local/lib
  with_fileglob:
    - "{{libs_dir}}/*"
  become: true

- name: install btree and rtree libs
  copy:
    src: "{{item}}"
    dest: /usr/local/lib
  with_fileglob:
    - "{{btree_src_dir}}/Build/libbtree*"
    - "{{rtree_src_dir}}/Build/librtree*"
  become: true

- name: sudo ldconfig
  shell: sudo ldconfig


- name: apt install libpq5
  apt:
    name: libpq5
    update_cache: yes
  become: true
