---
- name: clea datastructure
  shell: "{{item}}"
  with_items:
    - "rm -rf {{dtranx_dir}}/dtranx*.db0"
    - "rm -rf {{dtranx_dir}}/dtranx*.db1"
    - "rm -rf {{dtranx_dir}}/dtranx*.db2"
    - "rm -rf {{dtranx_dir}}/dtranx*.db3"
    - "rm -rf {{dtranx_dir}}/dtranx*.mapdb"
    - "rm -rf {{dtranx_dir}}/DTranx.log"
    - "rm -rf /mnt/mem/dtranx.log*"
    - "rm -rf /mnt/mem/gcdtranx.log*"


