---
# user bash to calculate throughput and latency

- name: remove existing throughput files if exist
  file:
    path: "{{benchmark_dir}}/{{db}}_{{item}}_list"
    state: absent
  with_items:
    - "throughput"
    - "latency"


- name: aggregate throughput file
  shell: grep -n workload ycsbc.out.{{item}} | awk '{print $4}' >> {{db}}_throughput_list
  args:
    chdir: "{{benchmark_dir}}"
  with_items: "{{groups['ycsbc_clients']}}" 

- name: calc total throughput
  shell: awk '{s+=$1} END {print s}' {{db}}_throughput_list > {{db}}_throughput_total
  args:
    chdir: "{{benchmark_dir}}"

- name: aggregate latency file
  shell: grep -n latency ycsbc.out.{{item}} | awk '{print $2}' >> {{db}}_latency_list
  args:
    chdir: "{{benchmark_dir}}"
  with_items: "{{groups['ycsbc_clients']}}" 

- name: calc avg latency
  shell: awk '{s+=$1} END {print s/NR}' {{db}}_latency_list > {{db}}_latency_avg
  args:
    chdir: "{{benchmark_dir}}"


#TODO:
#   1. Is the aggregate throughput/latency tasks tested yet?
#   2. In the total throughput/avg latency, why is the name *hyperdex*?
#   3. Add instant throughput aggregate, follow the lines 103-144 in TestAnalyzer.py in DTranx project
