---

- name: generate ips, copy workload files
  hosts: ycsbc_clients
  gather_facts: false
  roles:
    - roles/ycsbc/ycsbc-update-specs

# TODO: 
#   1. adjust operation count in the workload spec files
