---

- name: create benchmark directory if not exist
  command: mkdir -p {{benchmark_dir}}

- name: create benchmark directory if not exist
  raw: rm {{benchmark_dir}}/server.ips; touch {{benchmark_dir}}/server.ips

- name: generate server ips
  raw: "echo {{item}} >> {{benchmark_dir}}/server.ips"
  with_items: "{{servers}}"

- name: copy workload files
  copy:
    src: "{{item}}"
    dest: "{{benchmark_dir}}"
    mode: 0644
  with_items: "{{workloads}}"