---

- name: create benchmark directory if not exist
  command: mkdir -p {{benchmark_dir}}

- name: create benchmark directory if not exist
  raw: rm {{benchmark_dir}}/{{server_ips_filename}}; touch {{benchmark_dir}}/{{server_ips_filename}}

- name: generate server ips
  raw: "echo {{item}} >> {{benchmark_dir}}/{{server_ips_filename}}"
  with_items: "{{servers}}"

- name: copy workload files
  copy:
    src: "{{item}}"
    dest: "{{benchmark_dir}}"
    mode: 0644
#  with_items: "{{workloads_path}}"
  with_fileglob: "{{workload_files}}"

- name: copy ycsbc program
  copy:
    src: ycsbc
    dest: "{{benchmark_dir}}"
    mode: 0755
